### ISSUE TITLE
Systray support 

### ISSUE THREAD

**Issue by okratitan** [FyshOS/fynedesk#52]
Appindicatoe perhaps?

**Comment by AlbinoGeek** [comment]
`libappindicator` is considered to be deprecated by a number of Desktop Environments (most notably Gnome)

An alternative is xembed -- https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-latest.html

**Comment by okratitan** [comment]
I think you are confused. Gnome deprecated and does not use any systray support AFAIK.  Xembed is the old standard and most have deprecated it in favor of app indicator as it is newer and does not require X (Big due to the move to Wayland across the board)

**Comment by AlbinoGeek** [comment]
@okratitan Please correct me if I'm wrong (I want to be on this one...)

`appindicator` / `kappindicator` deprecation by Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956769

They noted that migrating to `ayatana-appindicator` was 100% API compatible and only required an import change.

---

GNOME deprecated the concept of "status icons" in general, and KDE followed:

https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

> In GNOME 3.26, the GNOME legacy tray is gone. Entirely.
> Out of the box in vanilla GNOME 3.26 you can not see or access status icons at all.

Some technical limitations listed:
- KStatusNotifier specification used by libappindicator is not good, bad serialization protocol
- libappindicator is unmaintained

(Of course, users can [and Ubuntu 20.04 does by default] install a Gnome extension which temporarily (until it breaks, because gnome-shell updates seem to break this every time it updates... eugh) restore the ability to have libappnotifier-based status icons.

One such ext (the one I use on Fedora for Steam, Skype and Discord -- the only three programs I have that still use status icons...) is: https://extensions.gnome.org/extension/615/appindicator-support/

---

You are correct about Xembed's limitations. That was me misreading the bug report, I apologize there.

---

The non-deprecated solution appears to be **D-Bus Status Notifier**

https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/

---

A light comparison of different SysTray-like features available per DE is available here:

https://islinuxabout.xyz/systray/

**Comment by andydotxyz** [comment]
This was completed over a year ago :)
